import { Device } from '@/types/device.types';

export const MOCK_DEVICES: Device[] = [
  {
    id: 'light-sala',
    name: 'Luz da Sala',
    category: 'lights',
    icon: '💡',
    status: 'online',
    isOn: true,
    room: 'Sala',
    brand: 'Philips Hue',
    lastSeen: new Date(),
    capabilities: [
      { type: 'toggle', property: 'isOn', label: 'Ligar/Desligar' },
      { type: 'range', property: 'brightness', label: 'Brilho', min: 0, max: 100, unit: '%' },
      { type: 'color', property: 'color', label: 'Cor' },
    ],
    state: { brightness: 80, color: '#FFFFFF', colorTemp: 4000 },
  },
  {
    id: 'light-quarto',
    name: 'Luz do Quarto',
    category: 'lights',
    icon: '💡',
    status: 'online',
    isOn: false,
    room: 'Quarto',
    brand: 'Philips Hue',
    lastSeen: new Date(),
    capabilities: [
      { type: 'toggle', property: 'isOn', label: 'Ligar/Desligar' },
      { type: 'range', property: 'brightness', label: 'Brilho', min: 0, max: 100, unit: '%' },
    ],
    state: { brightness: 60 },
  },
  {
    id: 'ac-sala',
    name: 'Ar-condicionado',
    category: 'ac',
    icon: '❄️',
    status: 'online',
    isOn: false,
    room: 'Sala',
    brand: 'LG',
    capabilities: [
      { type: 'toggle', property: 'isOn', label: 'Ligar/Desligar' },
      { type: 'range', property: 'temperature', label: 'Temperatura', min: 16, max: 30, unit: '°C' },
      { type: 'select', property: 'mode', label: 'Modo', options: ['cool', 'heat', 'fan', 'dry'] },
    ],
    state: { temperature: 22, mode: 'cool', fanSpeed: 'auto' },
  },
  {
    id: 'tv-sala',
    name: 'TV 4K',
    category: 'tv',
    icon: '📺',
    status: 'online',
    isOn: false,
    room: 'Sala',
    brand: 'Samsung',
    capabilities: [
      { type: 'toggle', property: 'isOn', label: 'Ligar/Desligar' },
      { type: 'range', property: 'volume', label: 'Volume', min: 0, max: 100, unit: '' },
    ],
    state: { volume: 30, input: 'HDMI 1' },
  },
  {
    id: 'speaker-sala',
    name: 'Sonos Speaker',
    category: 'speakers',
    icon: '🔊',
    status: 'online',
    isOn: false,
    room: 'Sala',
    brand: 'Sonos',
    capabilities: [
      { type: 'toggle', property: 'isOn', label: 'Ligar/Desligar' },
      { type: 'range', property: 'volume', label: 'Volume', min: 0, max: 100, unit: '%' },
    ],
    state: { volume: 45, playing: false, track: null },
  },
  {
    id: 'outlet-escritorio',
    name: 'Tomada Escritório',
    category: 'outlets',
    icon: '🔌',
    status: 'online',
    isOn: true,
    room: 'Escritório',
    brand: 'TP-Link',
    capabilities: [
      { type: 'toggle', property: 'isOn', label: 'Ligar/Desligar' },
      { type: 'readonly', property: 'power', label: 'Consumo', unit: 'W' },
    ],
    state: { power: 145 },
  },
  {
    id: 'sensor-porta',
    name: 'Sensor da Porta',
    category: 'sensors',
    icon: '🚪',
    status: 'online',
    isOn: true,
    room: 'Entrada',
    brand: 'Aqara',
    capabilities: [
      { type: 'readonly', property: 'isOpen', label: 'Estado' },
      { type: 'readonly', property: 'battery', label: 'Bateria', unit: '%' },
    ],
    state: { isOpen: false, battery: 87 },
  },
  {
    id: 'camera-entrada',
    name: 'Câmera Entrada',
    category: 'cameras',
    icon: '📷',
    status: 'online',
    isOn: true,
    room: 'Entrada',
    brand: 'Ring',
    capabilities: [
      { type: 'toggle', property: 'isOn', label: 'Ativar/Desativar' },
      { type: 'toggle', property: 'motionDetection', label: 'Detectar Movimento' },
    ],
    state: { motionDetection: true, recording: false },
  },
];
