import { Automation, Routine } from '@/types/automation.types';

export const PRESET_AUTOMATIONS: Automation[] = [
  {
    id: 'preset-boa-noite',
    name: 'Boa Noite',
    description: 'Apaga as luzes, desliga TV e ativa o modo noturno',
    emoji: '🌙',
    isActive: true,
    isPreset: true,
    trigger: { type: 'voice', config: { phrase: 'boa noite' }, label: 'Comando de voz: "Boa noite"' },
    actions: [
      { id: 'a1', type: 'device_control', config: { deviceId: 'light-sala', action: 'setOff' }, label: 'Apagar luz da sala', delayMs: 0 },
      { id: 'a2', type: 'device_control', config: { deviceId: 'light-quarto', action: 'setOn', property: 'brightness', value: 10 }, label: 'Luz do quarto fraca', delayMs: 500 },
      { id: 'a3', type: 'device_control', config: { deviceId: 'tv-sala', action: 'setOff' }, label: 'Desligar TV', delayMs: 0 },
      { id: 'a4', type: 'notification', config: { title: 'Modo noturno ativo' }, label: 'Notificação', delayMs: 1000 },
    ],
    createdAt: new Date(),
    runCount: 12,
    createdBy: 'preset',
  },
  {
    id: 'preset-indo-trabalhar',
    name: 'Indo Trabalhar',
    description: 'Prepara a casa para você sair',
    emoji: '💼',
    isActive: true,
    isPreset: true,
    trigger: { type: 'voice', config: { phrase: 'indo trabalhar' }, label: 'Comando: "Indo trabalhar"' },
    actions: [
      { id: 'b1', type: 'device_control', config: { deviceId: 'light-sala', action: 'setOff' }, label: 'Apagar todas as luzes', delayMs: 0 },
      { id: 'b2', type: 'device_control', config: { deviceId: 'ac-sala', action: 'setOff' }, label: 'Desligar AC', delayMs: 0 },
      { id: 'b3', type: 'notification', config: { title: 'Tem coisas ligadas?', body: 'Tomada do escritório ainda está ligada' }, label: 'Verificar tomadas', delayMs: 2000 },
    ],
    createdAt: new Date(),
    runCount: 28,
    createdBy: 'preset',
  },
  {
    id: 'preset-cheguei-casa',
    name: 'Cheguei em Casa',
    description: 'Bem-vindo de volta! Acende as luzes e lê os recados',
    emoji: '🏠',
    isActive: true,
    isPreset: true,
    trigger: { type: 'voice', config: { phrase: 'cheguei em casa' }, label: 'Comando: "Cheguei em casa"' },
    actions: [
      { id: 'c1', type: 'device_control', config: { deviceId: 'light-sala', action: 'setOn', property: 'brightness', value: 80 }, label: 'Acender luz da sala', delayMs: 0 },
      { id: 'c2', type: 'device_control', config: { deviceId: 'ac-sala', action: 'setOn' }, label: 'Ligar AC', delayMs: 500 },
    ],
    createdAt: new Date(),
    runCount: 31,
    createdBy: 'preset',
  },
  {
    id: 'preset-modo-foco',
    name: 'Modo Foco',
    description: 'Ambiente ideal para trabalho e concentração',
    emoji: '🎯',
    isActive: true,
    isPreset: true,
    trigger: { type: 'voice', config: { phrase: 'modo foco' }, label: 'Comando: "Modo foco"' },
    actions: [
      { id: 'd1', type: 'device_control', config: { deviceId: 'light-sala', action: 'setValue', property: 'brightness', value: 100 }, label: 'Luz no máximo', delayMs: 0 },
      { id: 'd2', type: 'play_media', config: { playlist: 'lofi', platform: 'spotify' }, label: 'Tocar Lo-Fi', delayMs: 500 },
      { id: 'd3', type: 'notification', config: { title: 'Modo foco ativo', body: 'Notificações silenciadas por 90min' }, label: 'Silenciar notificações', delayMs: 0 },
    ],
    createdAt: new Date(),
    runCount: 45,
    createdBy: 'preset',
  },
  {
    id: 'preset-cinema',
    name: 'Cinema',
    description: 'Luzes baixas, TV ligada, ambiente perfeito',
    emoji: '🎬',
    isActive: false,
    isPreset: true,
    trigger: { type: 'voice', config: { phrase: 'modo cinema' }, label: 'Comando: "Modo cinema"' },
    actions: [
      { id: 'e1', type: 'device_control', config: { deviceId: 'light-sala', action: 'setValue', property: 'brightness', value: 5 }, label: 'Luz na mínima', delayMs: 0 },
      { id: 'e2', type: 'device_control', config: { deviceId: 'tv-sala', action: 'setOn' }, label: 'Ligar TV', delayMs: 500 },
    ],
    createdAt: new Date(),
    runCount: 8,
    createdBy: 'preset',
  },
  {
    id: 'preset-academia',
    name: 'Academia',
    description: 'Energia máxima para o treino',
    emoji: '💪',
    isActive: true,
    isPreset: true,
    trigger: { type: 'voice', config: { phrase: 'vou treinar' }, label: 'Comando: "Vou treinar"' },
    actions: [
      { id: 'f1', type: 'play_media', config: { playlist: 'workout', platform: 'spotify' }, label: 'Música de treino', delayMs: 0 },
    ],
    createdAt: new Date(),
    runCount: 15,
    createdBy: 'preset',
  },
];

export const PRESET_ROUTINES: Routine[] = [
  {
    id: 'routine-manha',
    name: 'Modo Manhã',
    description: 'Seu briefing completo do dia',
    emoji: '☀️',
    isActive: true,
    steps: [
      {
        id: 'rs1',
        label: 'Verificar agenda',
        action: { id: 'a', type: 'api_call', config: { service: 'calendar' }, label: 'Agenda do dia' },
        isSpeaking: true,
        narration: 'Bom dia! Você tem 3 compromissos hoje. Às 10h reunião de equipe...',
      },
      {
        id: 'rs2',
        label: 'Clima do dia',
        action: { id: 'b', type: 'api_call', config: { service: 'weather' }, label: 'Previsão do tempo' },
        isSpeaking: true,
        narration: 'Hoje será ensolarado, máxima de 28 graus. Leve óculos de sol.',
      },
      {
        id: 'rs3',
        label: 'Notícias rápidas',
        action: { id: 'c', type: 'api_call', config: { service: 'news' }, label: 'Top 3 notícias' },
        isSpeaking: true,
        narration: 'As principais notícias de hoje são...',
      },
      {
        id: 'rs4',
        label: 'Verificar trânsito',
        action: { id: 'd', type: 'api_call', config: { service: 'maps' }, label: 'Situação do trânsito' },
        isSpeaking: true,
        narration: 'Seu trajeto para o trabalho está com 25 minutos hoje. Trânsito moderado.',
      },
    ],
  },
  {
    id: 'routine-dormir',
    name: 'Dormir',
    description: 'Preparar ambiente para descanso',
    emoji: '😴',
    isActive: true,
    steps: [
      {
        id: 'ss1',
        label: 'Apagar luzes',
        action: { id: 'a', type: 'device_control', config: { deviceId: 'light-sala', action: 'setOff' }, label: 'Luzes apagadas' },
        isSpeaking: true,
        narration: 'Iniciando modo sono. Apagando as luzes...',
      },
      {
        id: 'ss2',
        label: 'Ler agenda de amanhã',
        action: { id: 'b', type: 'api_call', config: { service: 'calendar' }, label: 'Agenda amanhã' },
        isSpeaking: true,
        narration: 'Amanhã você tem uma reunião às 9h. Boa noite!',
      },
    ],
  },
];
